### ISSUE TITLE
add "channel" property to rpc:log event

### ISSUE THREAD

**Issue by nombrekeff** [RobotUnion/rallf-python-sdk#6]
### Description
Task **rpc event** `log` should ideally have a channel parameter with the name of the task as the value.
To identify from wich task a log is.

Example:

```json
{
  "jsonrpc": "2.0",
  "method": "log",
  "params": {
    "message": " running command: run",
    "data": {},
    "channel": "my-task",
    "severity": 6
  }
}
```

**Comment by santoslluis** [comment]
maybe a better solution is to put the `fqtn` as the channel? confirm please

**Comment by santoslluis** [comment]
done
